name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > app/local.properties
          echo "MAPKIT_API_KEY=${{ secrets.MAPKIT_API_KEY }}" >> app/local.properties
          echo "SERVER_API_KEY=${{ secrets.SERVER_API_KEY }}" >> app/local.properties
          echo "VK_CLIENT=${{ secrets.VK_CLIENT }}" >> app/local.properties
          echo "VK_SECRET=${{ secrets.VK_SECRET }}" >> app/local.properties
          echo "KEY_NAME=${{ secrets.KEY_NAME }}" >> app/local.properties
          echo "KEY_PASS=${{ secrets.KEY_PASS }}" >> app/local.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> app/local.properties

      - name: Decrypt keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > your-key.jks

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk